name: CI

on:
  push:
    branches: [main, "release/**"]
    tags: ["v*"]           # publish job triggers on tags like v0.2.0
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Ruff lint
      run: ruff check src/ tests/

    - name: Run tests
      run: pytest -q

    - name: Build wheel
      run: |
        python -m pip install --upgrade pip build
        python -m build